"""secure notification tied instead of on giant global notification

Revision ID: 5f8771fcba62
Revises: c0ffee000001
Create Date: 2026-09-05 15:40:29.416766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8771fcba62'
down_revision: Union[str, Sequence[str], None] = 'c0ffee000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_orders_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_order_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_org_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_service_id'), table_name='service_orders')
    op.drop_table('service_orders')
    op.drop_index(op.f('ix_org_services_id'), table_name='org_services')
    op.drop_index(op.f('ix_org_services_organization_id'), table_name='org_services')
    op.drop_index(op.f('ix_org_services_service_id'), table_name='org_services')
    op.drop_table('org_services')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=150), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pricing_type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('service_img', sa.VARCHAR(length=150), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('rate', sa.FLOAT(), nullable=True),
    sa.Column('completed_at', sa.VARCHAR(length=40), nullable=True),
    sa.Column('isCompleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_services_service_id'), 'org_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_org_services_organization_id'), 'org_services', ['organization_id'], unique=False)
    op.create_index(op.f('ix_org_services_id'), 'org_services', ['id'], unique=False)
    op.create_table('service_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=150), nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('pricing_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('completed_at', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_orders_service_id'), 'service_orders', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_orders_org_id'), 'service_orders', ['org_id'], unique=False)
    op.create_index(op.f('ix_service_orders_order_id'), 'service_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_service_orders_id'), 'service_orders', ['id'], unique=False)
    # ### end Alembic commands ###
