"""add service uid column and org service table

Revision ID: e57222fdbd1e
Revises: b2c3d4e5f6a7
Create Date: 2026-09-03 12:26:55.510536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57222fdbd1e'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_org_employees_user_id'), 'org_employees', ['user_id'], unique=False)
    op.create_index(op.f('ix_org_members_user_id'), 'org_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_org_notifications_user_id'), 'org_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_org_shipments_market_order_id'), 'org_shipments', ['market_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_shipments_market_order_id'), table_name='org_shipments')
    op.drop_index(op.f('ix_org_notifications_user_id'), table_name='org_notifications')
    op.drop_index(op.f('ix_org_members_user_id'), table_name='org_members')
    op.drop_index(op.f('ix_org_employees_user_id'), table_name='org_employees')
    # ### end Alembic commands ###
