"""replace verification_token with verification_otp

Revision ID: f74c099dab6d
Revises: 4b0a0e274c4a
Create Date: 2026-05-08 17:36:39.903044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f74c099dab6d'
down_revision: Union[str, Sequence[str], None] = '4b0a0e274c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_otp_expires_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'verification_otp_expires_at')
    op.drop_column('users', 'verification_otp')
    # ### end Alembic commands ###
